version: '3.5'

services:
  sandbox.redis:
    image: redis/redis-stack
    container_name: sandbox.redis
    ports:
      - "6379:6379"
      - "6380:8001"
    networks:
      - sandbox.redis

networks:
  sandbox.redis:
    name: sandbox.redis
