### Spring ###
spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  # Messages
  messages:
    basename: locale/messages

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
