### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
