### Spring ###
spring:
  h2:
    console:
      enabled: true
      path: /h2

### SECURITY ###
security:
  oauth2:
    client:
      client-id: generic-client
      client-secret: abcd1234

### Server ###
server:
  port: 8000

### Logging ###
logging:
  level:
    org.springframework: DEBUG
    org.springframework.security.oauth2: DEBUG
    no.acntech: DEBUG
