### Spring ###
spring:
  h2:
    console:
      enabled: true
      path: /h2

### Server ###
server:
  port: 8000

### Logging ###
logging:
  level:
    org.springframework: DEBUG
    org.springframework.security.oauth2: DEBUG
    no.acntech: DEBUG
