### Spring ###
spring:
  # Application
  application:
    name: spring-boot-rest-api-jackson-module

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
