version: '3.5'

services:
  sandbox.postgres:
    image: postgres
    container_name: sandbox.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - sandbox.postgres:/var/lib/postgresql/data
      - ./resources/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    networks:
      - sandbox.postgres

volumes:
  sandbox.postgres:
    name: sandbox.postgres

networks:
  sandbox.postgres:
    name: sandbox.postgres
