version: '3.5'

services:
  acntech.postgres:
    image: postgres
    container_name: acntech.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - acntech.postgres:/var/lib/postgresql/data
      - ./resources/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    networks:
      - acntech.postgres

volumes:
  acntech.postgres:
    name: acntech.postgres

networks:
  acntech.postgres:
    name: acntech.postgres
