### Spring ###
spring:
  # Application
  application:
    name: spring-boot-elasticsearch-query-store
  # Elasticsearch
  elasticsearch:
    hosts:
      - http://localhost:9200
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sandbox;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:

### Server ###

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.elasticsearch.client: DEBUG
    no.acntech: DEBUG
