version: "3.7"

services:
  sandbox.keycloak:
    image: bitnami/keycloak
    container_name: sandbox.keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=abcd1234
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=abcd1234
      - KEYCLOAK_DATABASE_HOST=sandbox.postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=sandbox_keycloak
      - KEYCLOAK_DATABASE_USER=sandbox_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=abcd1234
    ports:
      - "8888:8080"
    networks:
      - sandbox.keycloak
      - sandbox.postgres

networks:
  sandbox.keycloak:
    name: sandbox.keycloak
  sandbox.postgres:
    name: sandbox.postgres
    external: true
