version: '3.5'

services:
  sandbox.keycloak.server:
    image: jboss/keycloak
    container_name: sandbox.keycloak.server
    depends_on:
      - sandbox.keycloak.database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=abcd1234
      - DB_VENDOR=postgres
      - DB_ADDR=sandbox.keycloak.database
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=abcd1234
    ports:
      - 8888:8080
    networks:
      - sandbox.keycloak

  sandbox.keycloak.database:
    image: postgres
    container_name: sandbox.keycloak.database
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=abcd1234
    networks:
      - sandbox.keycloak

networks:
  sandbox.keycloak:
    name: sandbox.keycloak
