version: '3.5'

services:
  sandbox_keycloak_server:
    image: jboss/keycloak
    container_name: sandbox_keycloak_server
    hostname: keycloak
    domainname: acntech.local
    depends_on:
      - sandbox_keycloak_database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=sandbox_keycloak_database
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=mV1IA6t2
    ports:
      - 8888:8080
    networks:
      - sandbox_keycloak

  sandbox_keycloak_database:
    image: postgres
    container_name: sandbox_keycloak_database
    hostname: database
    domainname: acntech.local
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=mV1IA6t2
    ports:
      - 5432:5432
    networks:
      - sandbox_keycloak

networks:
  sandbox_keycloak:
    name: sandbox_keycloak
