version: '3.5'

services:
  server:
    image: jboss/keycloak
    container_name: keycloak-server
    hostname: keycloak
    domainname: acntech.local
    depends_on:
      - database
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=mV1IA6t2
    ports:
      - 8888:8080
    networks:
      - keycloak

  database:
    image: postgres
    container_name: keycloak-database
    hostname: database
    domainname: acntech.local
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=mV1IA6t2
    ports:
      - 5432:5432
    networks:
      - keycloak

networks:
  keycloak:
    name: keycloak
