version: '3.5'

services:
  sandbox.keycloak:
    image: jboss/keycloak
    container_name: sandbox.keycloak
    ports:
      - "8888:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=abcd1234
      - DB_VENDOR=postgres
      - DB_ADDR=sandbox.postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=abcd1234
    networks:
      - sandbox.keycloak
      - sandbox.postgres

networks:
  sandbox.keycloak:
    name: sandbox.keycloak
  sandbox.postgres:
    name: sandbox.postgres
    external: true
