### Spring ###
spring:
  # Application
  application:
    name: spring-boot-basic-auth-oidc-webclient
  # Messages
  messages:
    basename: locale/messages
  # Security
  security:
    oauth2:
      client:
        registration:
          generic-client:
            provider: keycloak
            client-id: acntech-generic-client
            client-secret: abcdefgh12345678
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/acntech

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG
    web: DEBUG

### Server ###
server:
  port: 8080
