### Server ###
server:
  port: 8080
  servlet:
    context-path: /api

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Spring ###
spring:
  application:
    name: spring-boot-simple-jwt
  jackson:
    default-property-inclusion: NON_NULL
