# Server
server:
  port: 8080

# Logging
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

# Spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  messages:
    basename: locale/messages

  resources:
    cache-period: 31556926

  datasource:
    url: jdbc:postgresql://simple_mvc_postgres_database/foo
    username: foo
    password: abcd1234
    driver-class-name: org.postgresql.Driver
