version: '3.5'

services:
  sandbox.uaa.server:
    image: acntechie/uaa
    container_name: sandbox.uaa.server
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql,default
    volumes:
      - ./resources/uaa.yml:/usr/local/uaa/uaa.yml
    networks:
      - sandbox.uaa
      - sandbox.postgres

networks:
  sandbox.uaa:
    name: sandbox.uaa
  sandbox.postgres:
    name: sandbox.postgres
    external: true
