version: '3.5'

services:
  sandbox_uaa_server:
    image: acntechie/uaa
    container_name: sandbox_uaa_server
    hostname: uaa
    domainname: acntech.local
    depends_on:
      - sandbox_uaa_database
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql,default
    ports:
      - 8888:8080
    volumes:
      - ./uaa.yml:/usr/local/uaa/uaa.yml
    networks:
      - sandbox_uaa

  sandbox_uaa_database:
    image: postgres
    container_name: sandbox_uaa_database
    hostname: database
    domainname: acntech.local
    environment:
      - POSTGRES_DB=uaa
      - POSTGRES_USER=uaa
      - POSTGRES_PASSWORD=hS9y05zA
    networks:
      - sandbox_uaa

networks:
  sandbox_uaa:
    name: sandbox_uaa
