version: '3.5'

services:
  acntech.uaa:
    image: acntechie/uaa
    container_name: acntech.uaa
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql,default
    volumes:
      - ./resources/uaa.yml:/usr/local/uaa/uaa.yml
    networks:
      - acntech.uaa
      - acntech.postgres

networks:
  acntech.uaa:
    name: acntech.uaa
  acntech.postgres:
    name: acntech.postgres
    external: true
