### String ###
spring:
  # Application
  application:
    name: spring-boot-kafka
  # Kafka
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      client-id: ${spring.application.name}-consumer
      group-id: ${spring.application.name}-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "no.acntech.sandbox.model"
    producer:
      client-id: ${spring.application.name}-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
