### Server ###
server:
  port: 8080

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Spring ###
spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Messages
  messages:
    basename: locale/messages
