########################
# SPRING Configuration #
########################
spring:
  application:
    name: simple-oauth2-client-login
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  # JMX
  jmx:
    enabled: false
  # AOP
  aop:
    proxy-target-class: true
  # Messages
  messages:
    basename: locale/messages
  # Security
  security:
    oauth2:
      client:
        registration:
          generic-client:
            provider: uaa
            client-id: generic-client
            client-secret: o463qXwa
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          uaa:
            issuer-uri: http://localhost:8888/uaa/oauth/token

### Logging ###
logging:
  level:
    root: INFO
    web: INFO
    no.acntech: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

### Server ###
server:
  port: 8080
