version: '3.5'

services:
  sandbox_kafka_connect_elasticsearch_sink:
    image: acntechie/kafka
    container_name: sandbox_kafka_connect_elasticsearch_sink
    # ports:
    #   - 8083:8083
    volumes:
      - sandbox_kafka_connect_elasticsearch_sink:/var/lib/kafka
      - ./resources/connect-standalone.properties:/opt/kafka/default/config/connect-standalone.properties
      - ./resources/connect-elasticsearch-sink.properties:/opt/kafka/default/config/connect-elasticsearch-sink.properties
      - ./resources/plugins/kafka-connect-elasticsearch:/opt/kafka/default/plugins/kafka-connect-elasticsearch
    networks:
      - sandbox_kafka
      - sandbox_elasticsearch
    entrypoint: /opt/kafka/default/bin/connect-standalone.sh /opt/kafka/default/config/connect-standalone.properties /opt/kafka/default/config/connect-elasticsearch-sink.properties

volumes:
  sandbox_kafka_connect_elasticsearch_sink:
    name: sandbox_kafka_connect_elasticsearch_sink

networks:
  sandbox_kafka:
    name: sandbox_kafka
    external: true
  sandbox_elasticsearch:
    name: sandbox_elasticsearch
    external: true
