
CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255) not null,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

INSERT INTO USER (username, first_name, last_name) VALUES ('john', 'John', 'Doe');