version: '3.5'

services:
  sandbox_activemq_artemis:
    image: vromero/activemq-artemis
    container_name: sandbox_activemq_artemis
    hostname: activemq-artemis
    domainname: acntech.local
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - 8161:8161
      - 61616:61616
    networks:
      - sandbox_activemq_artemis

networks:
  sandbox_activemq_artemis:
    name: sandbox_activemq_artemis
