version: "3.7"

services:
  sandbox.keycloak-setup:
    image: bitnami/keycloak-config-cli
    container_name: sandbox.keycloak-setup
    environment:
      - KEYCLOAK_URL=http://sandbox.keycloak:8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=abcd1234
      - KEYCLOAK_LOGINREALM=master
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=60s
      - IMPORT_FILES_LOCATIONS=/config/*.json
    volumes:
      - ./resources/config:/config
    networks:
      - sandbox.keycloak

networks:
  sandbox.keycloak:
    name: sandbox.keycloak
    external: true
