########################
# SPRING Configuration #
########################
spring:
  application:
    name: spring-boot-webflux-resp-api

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
