### Server ###
server:
  port: 9090

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### AcnTech ###
acntech:
  workflow:
    base-url: http://localhost:8080/engine-rest
    response-timeout: 10S
    lock-duration: 1S