version: '3.5'

services:
  acntech_sandbox_kafka:
    image: acntechie/kafka:latest
    container_name: acntech-sandbox-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_HOSTS=acntech_sandbox_zookeeper:2181
    depends_on:
      - acntech_sandbox_zookeeper
    networks:
      - acntech_sandbox_simple_cqrs

  acntech_sandbox_zookeeper:
    image: acntechie/zookeeper:latest
    container_name: acntech-sandbox-zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=acntech_sandbox_zookeeper:2888:3888
    networks:
      - acntech_sandbox_simple_cqrs

networks:
  acntech_sandbox_simple_cqrs:
    name: acntech-sandbox-simple-cqrs
