########################
# SPRING Configuration #
########################
spring:
  application:
    name: simple-reactive-oauth2-resource-server
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  # JMX
  jmx:
    enabled: false
  # AOP
  aop:
    proxy-target-class: true
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/uaa/oauth/token

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
