version: '3.5'

services:
  sandbox.kafka:
    image: acntechie/kafka
    container_name: sandbox.kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://sandbox.kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ZOOKEEPER_HOSTS=sandbox.zookeeper:2181
    depends_on:
      - sandbox.zookeeper
    volumes:
      - sandbox.kafka:/var/lib/kafka
    networks:
      - sandbox.kafka

  sandbox.zookeeper:
    image: acntechie/zookeeper
    container_name: sandbox.zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=sandbox.zookeeper:2888:3888
    volumes:
      - sandbox.zookeeper:/var/lib/zookeeper
    networks:
      - sandbox.kafka

volumes:
  sandbox.kafka:
    name: sandbox.kafka
  sandbox.zookeeper:
    name: sandbox.zookeeper

networks:
  sandbox.kafka:
    name: sandbox.kafka
