version: '3.5'

services:
  sandbox.kafka:
    image: bitnami/kafka
    container_name: sandbox.kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=sandbox.zookeeper:2181
    depends_on:
      - sandbox.zookeeper
    volumes:
      - sandbox.kafka:/bitnami/kafka
    networks:
      - sandbox.kafka

  sandbox.zookeeper:
    image: bitnami/zookeeper
    container_name: sandbox.zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - sandbox.zookeeper:/bitnami/zookeeper
    networks:
      - sandbox.kafka

volumes:
  sandbox.kafka:
    name: sandbox.kafka
  sandbox.zookeeper:
    name: sandbox.zookeeper

networks:
  sandbox.kafka:
    name: sandbox.kafka
