version: '3.5'

services:
  sandbox_kafka:
    image: acntechie/kafka
    container_name: sandbox_kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://sandbox_kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - ZOOKEEPER_HOSTS=sandbox_zookeeper:2181
    depends_on:
      - sandbox_zookeeper
    volumes:
      - sandbox_kafka:/var/lib/kafka
    networks:
      - sandbox_kafka

  sandbox_zookeeper:
    image: acntechie/zookeeper
    container_name: sandbox_zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=sandbox_zookeeper:2888:3888
    volumes:
      - sandbox_zookeeper:/var/lib/zookeeper
    networks:
      - sandbox_kafka

volumes:
  sandbox_kafka:
    name: sandbox_kafka
  sandbox_zookeeper:
    name: sandbox_zookeeper

networks:
  sandbox_kafka:
    name: sandbox_kafka
