### AcnTech ###
acntech:
  webservice:
    endpoint:
      path: /v1.0/simple
    client:
      url: http://localhost:${server.port}${cxf.path}${acntech.webservice.endpoint.path}

### Server ###
server:
  port: 8080

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Spring ###
spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Messages
  messages:
    basename: locale/messages

### Webservice ###
cxf:
  path: /ws
