version: '3.5'

services:
  sandbox_elasticsearch:
    image: elasticsearch:7.14.0
    container_name: sandbox_elasticsearch
    hostname: elasticsearch
    domainname: acntech.local
    environment:
      - node.name=sandbox_elasticsearch_01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - sandbox_elasticsearch:/usr/share/elasticsearch/data
    networks:
      - sandbox_elasticsearch

volumes:
  sandbox_elasticsearch:
    name: sandbox_elasticsearch

networks:
  sandbox_elasticsearch:
    name: sandbox_elasticsearch
