version: '3.5'

services:
  sandbox.kibana:
    image: kibana:7.14.1
    container_name: sandbox.kibana
    depends_on:
      - sandbox.elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://sandbox.elasticsearch:9200
    networks:
      - sandbox.elasticsearch

  sandbox.elasticsearch:
    image: elasticsearch:7.14.1
    container_name: sandbox.elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=sandbox.elasticsearch.01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - sandbox.elasticsearch:/usr/share/elasticsearch/data
    networks:
      - sandbox.elasticsearch

volumes:
  sandbox.elasticsearch:
    name: sandbox.elasticsearch

networks:
  sandbox.elasticsearch:
    name: sandbox.elasticsearch
