########################
# SPRING Configuration #
########################
spring:
  application:
    name: spring-boot-oidc-resource-server
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE-DATES-AS-TIMESTAMPS: false
    deserialization:
      ADJUST-DATES-TO-CONTEXT-TIME-ZONE: false
  # JMX
  jmx:
    enabled: false
  # AOP
  aop:
    proxy-target-class: true
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/acntech

### Logging ###
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
  servlet:
    context-path: /api
