version: "3"

services:
  simple_postgres_database:
    image: postgres
    container_name: simple_postgres_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_ROOT_PASSWORD=abcd1234
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - simple_postgres

networks:
  simple_postgres:
