version: "3"

services:
  simple_mvc_postgres_webapp:
    image: simple-mvc-postgres-webapp:1.0.1-SNAPSHOT
    container_name: simple_mvc_postgres_webapp
    ports:
      - 8080:8080
    depends_on:
      - simple_mvc_postgres_database
    networks:
      - simple_mvc_postgres
    build:
      context: .
      args:
        - APPLICATION_NAME=simple-mvc-postgres-webapp

  simple_mvc_postgres_database:
    image: postgres
    container_name: simple_mvc_postgres_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_ROOT_PASSWORD=abcd1234
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - simple_mvc_postgres

  simple_mvc_postgres_admin:
    image: adminer
    container_name: simple_mvc_postgres_admin
    ports:
      - 8090:8080
    depends_on:
      - simple_mvc_postgres_database
    networks:
      - simple_mvc_postgres


networks:
  simple_mvc_postgres:
