### Server ###
server:
  port: 8080

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG
    web: DEBUG

### Spring ###
spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Messages
  messages:
    basename: locale/messages

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foo
    username: foo
    password: abcd1234
