CREATE TABLE ROLES
(
    ROLE        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ROLES_ROLE PRIMARY KEY (ROLE)
);

CREATE TABLE USERS
(
    USERNAME   VARCHAR(255) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USERS_USERNAME PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_ROLES
(
    USERNAME VARCHAR(255) NOT NULL,
    ROLE     VARCHAR(255) NOT NULL,
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE) REFERENCES ROLES (ROLE)
);
