### Spring ###
spring:
  # Application
  application:
    name: spring-boot-elasticsearch
  # Elasticsearch
  elasticsearch:
    hosts:
      - localhost:9200

### Server ###

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG
