### AcnTech ###
acntech:
  webservice:
    url: http://localhost:8080/ws/v1/greeting

### Server ###
server:
  port: 8081

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Spring ###
spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Messages
  messages:
    basename: locale/messages
