########################
# SPRING Configuration #
########################
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: all
          uri: http://localhost:8080
          predicates:
            - Path=/**

### Logging ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG
    org.springframework.boot: INFO
    org.springframework.cloud: TRACE
    org.springframework.web: INFO

### Server ###
server:
  port: 8000
