### Webservice ###
cxf:
  path: /ws

### Spring ###
spring:
  # Application
  application:
    name: spring-boot-webservice-endpoint-cxf
  # Messages
  messages:
    basename: locale/messages

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8081
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false

