### AcnTech ###
acntech:
  webservice:
    url: http://localhost:8081/ws/v1/greeting

### Spring ###
spring:
  # Application
  application:
    name: spring-boot-webservice-client-cxf
  # Messages
  messages:
    basename: locale/messages

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
