### Spring ###
spring:
  # Application
  application:
    name: spring-boot-kotlin-grps-server

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 8090
