version: '3.5'

services:
  sandbox.activemq:
    image: webcenter/activemq
    container_name: sandbox.activemq
    environment:
      - ACTIVEMQ_CONFIG_NAME=acntech-sandbox-activemq
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=abcd1234
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    networks:
      - sandbox.activemq

networks:
  sandbox.activemq:
    name: sandbox.activemq
