version: '3.5'

services:
  sandbox_activemq:
    image: webcenter/activemq
    container_name: sandbox_activemq
    hostname: activemq
    domainname: acntech.local
    environment:
      - ACTIVEMQ_CONFIG_NAME=acntech-sandbox-activemq
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    networks:
      - sandbox_activemq

networks:
  sandbox_activemq:
    name: sandbox_activemq
