########################
# SPRING Configuration #
########################
spring:
  application:
    name: spring-boot-oidc-client-login-stateless
  # Jackson
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  # JMX
  jmx:
    enabled: false
  # AOP
  aop:
    proxy-target-class: true
  # Messages
  messages:
    basename: locale/messages
  # Security
  security:
    oauth2:
      client:
        registration:
          generic-client-login:
            provider: keycloak
            client-id: generic-client-login
            client-secret: w1Mp8ziW
            scope:
              - openid
              - profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/uaa/oauth/token

### Logging ###
logging:
  level:
    root: INFO
    web: INFO
    no.acntech: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

### Server ###
server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
