# Server
server:
  port: 8080

# Logging
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

spring:
  # Web
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  messages:
    basename: locale/messages

  resources:
    cache:
      period: 31556926

  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prototype;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  # Enable H2 database console
  h2:
    console:
      enabled: true
