CREATE TABLE "USER_ROLES"
(
  USERNAME VARCHAR(255) NOT NULL
  ,
  ROLE     VARCHAR(255) NOT NULL
  ,
  CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USERNAME) REFERENCES "USERS" (USERNAME)
  ,
  CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE) REFERENCES "ROLES" (ROLE)
);

INSERT INTO "USER_ROLES"
(USERNAME, ROLE)
VALUES
  ('user', 'USER');

INSERT INTO "USER_ROLES"
(USERNAME, ROLE)
VALUES
  ('admin', 'USER');

INSERT INTO "USER_ROLES"
(USERNAME, ROLE)
VALUES
  ('admin', 'ADMIN');
