CREATE TABLE "ROLES"
(
  ROLE        VARCHAR(255) NOT NULL
  ,
  DESCRIPTION VARCHAR(255) NOT NULL
  ,
  CONSTRAINT PK_ROLES_ROLE PRIMARY KEY (ROLE)
);

INSERT INTO "ROLES"
(ROLE, DESCRIPTION)
VALUES
  ('USER', 'Standard user');

INSERT INTO "ROLES"
(ROLE, DESCRIPTION)
VALUES
  ('ADMIN', 'Administrator');
